<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>JTS.WindowsCompanion</RootNamespace>
    <AssemblyName>JTS.WindowsCompanion.Core</AssemblyName>
  </PropertyGroup>
  <ItemGroup Condition="'$(CompanionReleasePublicKeyPath)' != ''">
    <EmbeddedResource Include="$(CompanionReleasePublicKeyPath)" LogicalName="JTS.Companion.ReleasePublicKey" />
  </ItemGroup>
</Project>
